modify git hook to push the bumpversion changes

diff --git a/.githooks/pre-push b/.githooks/pre-push
--- a/.githooks/pre-push
+++ b/.githooks/pre-push
@@ -1,25 +1,11 @@
 #!/bin/sh
-
-# An example hook script to verify what is about to be pushed.  Called by "git
-# push" after it has checked the remote status, but before anything has been
-# pushed.  If this script exits with a non-zero status nothing will be pushed.
-#
-# This hook is called with the following parameters:
-#
-# $1 -- Name of the remote to which the push is being done
-# $2 -- URL to which the push is being done
-#
-# If pushing without using a named remote those arguments will be equal.
-#
-# Information about the commits which are being pushed is supplied as lines to
-# the standard input in the form:
-#
-#   <local ref> <local sha1> <remote ref> <remote sha1>
-
-echo "Please provide the type of changes you are going to push"
-
-# Read user input, assign stdin to keyboard
-exec < /dev/tty
+# Define colors for echo output
+RED='\033[0;31m'
+GREEN='\033[0;32m'
+YELLOW='\033[1;33m'
+ORANGE='\033[0;33m'
+PURPLE='\033[0;35m'
+NC='\033[0m' # No Color
 
 # Run linting
 make lint
@@ -41,22 +27,26 @@ else
   exit 1;
 fi
 
+echo "Please provide the type of changes you just commit"
+# Read user input, assign stdin to keyboard
+exec < /dev/tty
+
 # Bumpversion to rigth one.
 while read -p "Is this a breaking change? (y/N) " yn; do
     case $yn in
-        [Yy] ) (bumpversion mayor; git push --no-verify); exit 0;;
+        [Yy] ) bumpversion mayor; git push --no-verify; echo "${GREEN}Push ${ORANGE}using ${YELLOW}githook.${PURPLE} Please ignore the ${RED}error !!!"; exit 1;;
         * ) break;;
 	esac
 done
 while read -p "Are you fixing a bug? (y/N) " yn; do
     case $yn in
-        [Yy] ) (bumpversion patch; git push --no-verify); exit 0;;
+        [Yy] ) bumpversion patch; git push --no-verify; echo "${GREEN}Push ${ORANGE}using ${YELLOW}githook.${PURPLE} Please ignore the ${RED}error !!!"; exit 1;;
         * ) break;;
     esac
 done
 while read -p "Is this a new feature? (y/N) " yn; do
     case $yn in
-        [Yy] ) (bumpversion minor; git push --no-verify); exit 0;;
+        [Yy] ) bumpversion minor; git push --no-verify; echo "${GREEN}Push ${ORANGE}using ${YELLOW}githook.${PURPLE} Please ignore the ${RED}error !!!"; exit 1;;
         * ) break;;
     esac
 done
